/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardUIServices.framework/SpringBoardUIServices
 */

@interface SBEmptyButtonView : UIView <TPNumberPadButtonProtocol> {
    unsigned int  _char;
}

@property unsigned int character;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

// Image: /System/Library/PrivateFrameworks/SpringBoardUIServices.framework/SpringBoardUIServices

- (unsigned int)character;
- (id)initForCharacter:(unsigned int)arg1;
- (struct CGSize { double x1; double x2; })intrinsicContentSize;
- (void)setCharacter:(unsigned int)arg1;

// Image: /System/Library/AccessibilityBundles/SpringBoardUIServices.axbundle/SpringBoardUIServices

+ (Class)safeCategoryBaseClass;

- (bool)_accessibilityIsScannerElement;

@end
