/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardUIServices.framework/SpringBoardUIServices
 */

@interface SBUIPasscodeTextField : UITextField

// Image: /System/Library/PrivateFrameworks/SpringBoardUIServices.framework/SpringBoardUIServices

- (void)_handleKeyUIEvent:(id)arg1;
- (bool)becomeFirstResponder;
- (void)dealloc;
- (bool)resignFirstResponder;

// Image: /System/Library/AccessibilityBundles/SpringBoardUIServices.axbundle/SpringBoardUIServices

+ (Class)safeCategoryBaseClass;

- (bool)_accessibilitySupportsHandwriting;
- (id)accessibilityLabel;
- (id)accessibilityValue;
- (void)deleteBackward;
- (void)insertText:(id)arg1;
- (bool)isAccessibilityElement;

@end
