/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PreferencesUI.framework/PreferencesUI
 */

@interface PSUIExplicitCell : PSSwitchTableCell

// Image: /System/Library/PrivateFrameworks/PreferencesUI.framework/PreferencesUI

- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;
- (void)setCellEnabled:(bool)arg1;

// Image: /System/Library/AccessibilityBundles/PreferencesUI.axbundle/PreferencesUI

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (bool)isAccessibilityElement;

@end
