/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PreferencesUI.framework/PreferencesUI
 */

@interface PSUIColorTemperatureSliderTableCell : PSSliderTableCell {
    UILabel * _coolerLabel;
    UILabel * _warmerLabel;
}

// Image: /System/Library/PrivateFrameworks/PreferencesUI.framework/PreferencesUI

+ (double)preferredHeight;

- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;
- (void)layoutSubviews;

// Image: /System/Library/AccessibilityBundles/PreferencesUI.axbundle/PreferencesUI

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (id)accessibilityValue;

@end
