/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
 */

@interface _HKMedicalIDMultilineStringCell : UITableViewCell {
    NSString * _stringValue;
    UITextView * _textLabel;
    UILabel * _titleLabel;
}

@property (getter=isBodyTextInteractive, nonatomic) bool bodyTextInteractive;
@property (nonatomic, retain) NSString *stringValue;
@property (nonatomic, retain) NSString *title;

// Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI

- (void).cxx_destruct;
- (void)_contentSizeCategoryDidChange:(id)arg1;
- (void)dealloc;
- (bool)isBodyTextInteractive;
- (void)layoutSubviews;
- (void)setBodyTextInteractive:(bool)arg1;
- (void)setStringValue:(id)arg1;
- (void)setTitle:(id)arg1;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;
- (id)stringValue;
- (id)title;

// Image: /System/Library/AccessibilityBundles/HealthUI.axbundle/HealthUI

+ (Class)safeCategoryBaseClass;

- (void)_accessibilityLoadAccessibilityInformation;
- (id)accessibilityLabel;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end
