/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIAccessibility.framework/UIAccessibility
 */

@interface __NSObjectAccessibility_super : UIAccessibilitySafeCategory

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (id)accessibilityElementAtIndex:(long long)arg1;
- (long long)accessibilityElementCount;
- (long long)indexOfAccessibilityElement:(id)arg1;
- (void)setAccessibilityElements:(id)arg1;

@end
