/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIAccessibility.framework/UIAccessibility
 */

@interface __NSStringImageProcessingAccessibility_super : UIAccessibilitySafeCategory

// Image: /System/Library/PrivateFrameworks/UIAccessibility.framework/UIAccessibility

+ (Class)safeCategoryBaseClass;

// Image: /System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation

- (void)drawAtPoint:(struct CGPoint { double x1; double x2; })arg1 withAttributes:(id)arg2;
- (void)drawInRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 withAttributes:(id)arg2;

@end
