/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIAccessibility.framework/UIAccessibility
 */

@interface __UIPrintPanelTableViewControllerAccessibility_super : UIAccessibilitySafeCategory

// Image: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit

+ (Class)safeCategoryBaseClass;

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)updateCopies:(id)arg1;

@end
