/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIAccessibility.framework/UIAccessibility
 */

@interface __UIAccessibilityElementSuperCategory_super : UIAccessibilitySafeCategory

// Image: /System/Library/PrivateFrameworks/UIAccessibility.framework/UIAccessibility

+ (Class)safeCategoryBaseClass;

- (float)_accessibilityActivationDelay;
- (id)_accessibilityAutomaticIdentifier;
- (bool)_accessibilitySetNativeFocus;
- (void)_accessibilitySetValue:(id)arg1;
- (bool)_accessibilitySupportsActivateAction;
- (bool)_accessibilitySupportsHandwriting;
- (bool)_accessibilityViewHierarchyHasNativeFocus;
- (bool)accessibilityActivate;
- (void)accessibilityDecrement;
- (void)accessibilityElementDidBecomeFocused;
- (void)accessibilityElementDidLoseFocus;
- (void)accessibilityIncrement;
- (void)accessibilityZoomInAtPoint:(struct CGPoint { double x1; double x2; })arg1;
- (void)accessibilityZoomOutAtPoint:(struct CGPoint { double x1; double x2; })arg1;

// Image: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation

- (id)description;

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (struct CGPoint { double x1; double x2; })accessibilityActivationPoint;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })accessibilityFrame;
- (id)accessibilityHint;
- (id)accessibilityLabel;
- (id)accessibilityLanguage;
- (id)accessibilityPath;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityValue;
- (id)initWithAccessibilityContainer:(id)arg1;
- (bool)isAccessibilityElement;

// Image: /usr/lib/libobjc.A.dylib

- (void)dealloc;
- (id)init;

@end
