/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKPassPaymentCardFrontFaceView : PKPassFrontFaceView

// Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI

- (id)shortFaceTemplate;
- (id)shortScrunchedFaceTemplate;
- (bool)showsShare;
- (id)tallFaceTemplate;

// Image: /System/Library/AccessibilityBundles/PassKitFramework.axbundle/PassKitFramework

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (bool)isAccessibilityElement;

@end
