/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKPaymentAuthorizationItemCell : PKTableViewCell {
    UIImageView * _alertView;
    UIImageView * _arrowView;
    NSMutableArray * _constraints;
    NSString * _label;
    UILabel * _labelView;
    PKPaymentAuthorizationLayout * _layout;
    UIView * _separatorView;
    NSString * _value;
    NSMutableArray * _valueViews;
}

@property (nonatomic, copy) NSString *label;
@property (nonatomic, copy) NSString *value;

// Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI

- (void).cxx_destruct;
- (id)_createValueView;
- (id)addValue:(id)arg1 isPlaceholder:(bool)arg2;
- (void)dealloc;
- (id)initWithLayout:(id)arg1 reuseIdentifier:(id)arg2;
- (id)label;
- (void)prepareForReuse;
- (void)setLabel:(id)arg1;
- (void)setValue:(id)arg1;
- (void)setValue:(id)arg1 isPlaceholder:(bool)arg2;
- (void)updateConstraints;
- (id)value;

// Image: /System/Library/AccessibilityBundles/PassKitFramework.axbundle/PassKitFramework

+ (Class)safeCategoryBaseClass;

- (void)_accessibilityLoadAccessibilityInformation;
- (void)_createSubviews;
- (unsigned long long)accessibilityTraits;

@end
