/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKWelcomeHeaderView : UIView {
    UIButton * _actionButton;
    UIActivityIndicatorView * _activityIndicator;
    UILabel * _environmentLabel;
    NSString * _hintingLabel;
    unsigned long long  _passType;
    bool  _showActivityIndicator;
    bool  _showSEHinting;
    UIView * _titleView;
}

@property (nonatomic, copy) NSString *hintingLabel;
@property (nonatomic, readonly) unsigned long long passType;
@property (nonatomic) bool showActivityIndicator;
@property (nonatomic) bool showSEHinting;

// Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI

- (void).cxx_destruct;
- (void)_addTapped;
- (void)addTapped;
- (id)hintingLabel;
- (id)init;
- (void)layoutSubviews;
- (unsigned long long)passType;
- (void)setHintingLabel:(id)arg1;
- (void)setShowActivityIndicator:(bool)arg1;
- (void)setShowSEHinting:(bool)arg1;
- (bool)showActivityIndicator;
- (bool)showSEHinting;

// Image: /System/Library/AccessibilityBundles/PassKitFramework.axbundle/PassKitFramework

+ (Class)safeCategoryBaseClass;

- (void)_accessibilityLoadAccessibilityInformation;
- (id)initWithPassType:(unsigned long long)arg1;

@end
