/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@interface PSUsageSizeHeader : UIView <PSHeaderFooterView> {
    double  _height;
    UILabel * _sizeLabel;
    UILabel * _titleLabel;
}

// Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences

- (void).cxx_destruct;
- (id)initWithSpecifier:(id)arg1;
- (void)layoutSubviews;
- (double)preferredHeightForWidth:(double)arg1;
- (void)setSize:(id)arg1;
- (void)setSizeLabelHidden:(bool)arg1;

// Image: /System/Library/AccessibilityBundles/PreferencesFramework.axbundle/PreferencesFramework

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (bool)isAccessibilityElement;

@end
