/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
 */

@interface CNPickerItemCell : UITableViewCell {
    UITextField * _textField;
}

@property (nonatomic, retain) UITextField *textField;

// Image: /System/Library/Frameworks/ContactsUI.framework/ContactsUI

- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
- (void)setTextField:(id)arg1;
- (id)textField;

// Image: /System/Library/AccessibilityBundles/ContactsUI.axbundle/ContactsUI

+ (Class)safeCategoryBaseClass;

- (id)_accessibilityTextViewTextOperationResponder;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityValue;
- (void)beginEditing;
- (void)endEditing;
- (bool)isAccessibilityElement;

@end
