/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
 */

@interface CNPropertyLabelButton : UIButton

// Image: /System/Library/Frameworks/ContactsUI.framework/ContactsUI

+ (id)propertyLabelButton;

// Image: /System/Library/AccessibilityBundles/ContactsUI.axbundle/ContactsUI

+ (Class)safeCategoryBaseClass;

- (id)accessibilityHint;

@end
