/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
 */

@interface CNPropertyPlaceholderCell : CNLabeledCell {
    UILabel * _label;
}

@property (nonatomic, readonly) UILabel *label;

// Image: /System/Library/Frameworks/ContactsUI.framework/ContactsUI

- (void).cxx_destruct;
- (id)label;
- (id)labelView;
- (double)minCellHeight;
- (void)setCardGroupItem:(id)arg1;
- (bool)shouldPerformDefaultAction;

// Image: /System/Library/AccessibilityBundles/ContactsUI.axbundle/ContactsUI

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;

@end
