/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
 */

@interface CNPropertyPhoneNumberCell : CNPropertySimpleTransportCell

// Image: /System/Library/Frameworks/ContactsUI.framework/ContactsUI

- (void)setProperty:(id)arg1;
- (bool)shouldPerformDefaultAction;
- (void)updateTransportButtons;

// Image: /System/Library/AccessibilityBundles/ContactsUI.axbundle/ContactsUI

+ (Class)safeCategoryBaseClass;

- (id)accessibilityValue;

@end
