/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

@interface ABContactCell : CNContactCell

// Image: /System/Library/AccessibilityBundles/AddressBookUIFramework.axbundle/AddressBookUIFramework

+ (Class)safeCategoryBaseClass;

- (bool)_accessibilityHitTestReverOrder;
- (bool)_accessibilityHitTestShouldFallbackToNearestChild;
- (bool)_accessibilityTableViewCellSubclassShouldExist;

@end
