/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

@interface ABHighlightingTextField : UITextField {
    UIColor * _highlightedTextColor;
    bool  _isHighlighted;
    bool  _isHighlightingEnabled;
    <ABResponderDelegate> * _responderDelegate;
    UIColor * _savedTextColor;
    bool  _showsClearButtonWhenEmpty;
}

@property (setter=abSetHighlightedTextColor:, nonatomic, retain) UIColor *abHighlightedTextColor;
@property (setter=abSetHighlighted:, nonatomic) bool abIsHighlighted;
@property (setter=abSetHighlightingEnabled:, nonatomic) bool abIsHighlightingEnabled;
@property (nonatomic) <ABResponderDelegate> *responderDelegate;
@property (nonatomic) bool showsClearButtonWhenEmpty;

// Image: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI

- (id)_nextKeyResponder;
- (id)_previousKeyResponder;
- (bool)_showsClearButtonWhenEmpty;
- (id)abHighlightedTextColor;
- (bool)abIsHighlighted;
- (bool)abIsHighlightingEnabled;
- (void)abSetHighlighted:(bool)arg1;
- (void)abSetHighlightedTextColor:(id)arg1;
- (void)abSetHighlightingEnabled:(bool)arg1;
- (bool)becomeFirstResponder;
- (void)dealloc;
- (id)responderDelegate;
- (void)setResponderDelegate:(id)arg1;
- (void)setShowsClearButtonWhenEmpty:(bool)arg1;
- (void)setTextColor:(id)arg1;
- (bool)showsClearButtonWhenEmpty;

// Image: /System/Library/AccessibilityBundles/AddressBookUIFramework.axbundle/AddressBookUIFramework

+ (Class)safeCategoryBaseClass;

- (bool)accessibilityElementsHidden;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })accessibilityFrame;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;

@end
