/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

@interface PLMessageUIProxy : NSObject

// Image: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary

+ (Class)MFComposeRecipientClass;
+ (Class)MFComposeRecipientViewClass;
+ (Class)MFContactsSearchManagerClass;
+ (Class)MFContactsSearchResultsModelClass;
+ (Class)MFRecipientTableViewCellClass;
+ (Class)MFSearchShadowViewClass;
+ (bool)canSendMail;
+ (id)newABUnknownPersonViewControllerWithEmailAddress:(id)arg1;
+ (id)newComposeViewController;

// Image: /System/Library/AccessibilityBundles/PhotoLibraryFramework.axbundle/PhotoLibraryFramework

+ (Class)MFMailComposeViewControllerClass;
+ (Class)safeCategoryBaseClass;

@end
