/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIAlertMediaButton : UIAlertButton {
    UIImageView * _checkmarkView;
    UIImage * _highlightedTableIcon;
    UIImage * _tableIcon;
}

@property (nonatomic, readonly) UIImageView *checkmarkView;
@property (nonatomic, retain) UIImage *highlightedTableIcon;
@property (nonatomic, retain) UIImage *tableIcon;

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (id)checkmarkView;
- (void)dealloc;
- (id)highlightedTableIcon;
- (void)layoutSubviews;
- (void)setHighlightedTableIcon:(id)arg1;
- (void)setTableIcon:(id)arg1;
- (id)tableIcon;

// Image: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;

@end
