/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIClassicWindow : UIWindow

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (double)_adjustedWindowLevelFromLevel:(double)arg1;
- (bool)_isConstrainedByScreenJail;
- (bool)_shouldZoom;
- (void)_updateTransformLayerForClassicPresentation;

// Image: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit

+ (Class)safeCategoryBaseClass;

- (bool)_accessibilityWindowVisible;

@end
