/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIImageNibPlaceholder : UIImage <NSCoding> {
    NSString * runtimeResourceName;
}

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (void).cxx_destruct;
- (id)_initWithOtherImage:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithContentsOfFile:(id)arg1 andRuntimeResourceName:(id)arg2;

// Image: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit

+ (Class)safeCategoryBaseClass;

- (id)initWithCoder:(id)arg1;
- (id)initWithData:(id)arg1 andRuntimeResourceName:(id)arg2;

@end
