/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIInputSwitcherTableView : UITableView {
    UIKeyboardMenuView * _menu;
}

@property (nonatomic) UIKeyboardMenuView *menu;

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (void)deselectRowAtIndexPath:(id)arg1 animated:(bool)arg2;
- (id)menu;
- (void)selectRowAtIndexPath:(id)arg1 animated:(bool)arg2 scrollPosition:(long long)arg3;
- (void)setMenu:(id)arg1;

// Image: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit

+ (Class)safeCategoryBaseClass;

- (id)accessibilityIdentifier;

@end
