/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKBCandidateCollectionView : UICollectionView

@property (nonatomic, readonly) NSIndexPath *selectedItemIndexPath;

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (bool)_selectAndScrollToItemAtIndexPath:(id)arg1 animated:(bool)arg2 scrollPosition:(unsigned long long)arg3;
- (void)configureAsCandidatesBar;
- (bool)delaysContentTouches;
- (id)selectedItemIndexPath;

// Image: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit

+ (Class)safeCategoryBaseClass;

- (bool)isAccessibilityOpaqueElementProvider;

@end
