/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKBEmojiSnapshotSizingView : UIView {
    struct CGSize { 
        double width; 
        double height; 
    }  _snapshotSize;
    UIView * _snapshotView;
}

@property (nonatomic, readonly) UIView *snapshotView;

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (void)dealloc;
- (id)initWithSnapshotView:(id)arg1;
- (void)layoutSubviews;
- (id)snapshotView;

// Image: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (bool)isAccessibilityElement;

@end
