/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKeyboardEmojiCollectionViewCell : UICollectionViewCell {
    UIKeyboardEmoji * _emoji;
    UILabel * _emojiLabel;
}

@property (nonatomic, copy) UIKeyboardEmoji *emoji;
@property (nonatomic) long long emojiFontSize;

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (void).cxx_destruct;
- (id)debugDescription;
- (id)emoji;
- (long long)emojiFontSize;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setEmojiFontSize:(long long)arg1;

// Image: /System/Library/AccessibilityBundles/ChatKitFramework.axbundle/ChatKitFramework

+ (Class)safeCategoryBaseClass;

- (id)accessibilityCustomRotors;

// Image: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit

- (bool)_accessibilityAllowsAlternativeCharacterActivation;
- (id)_accessibilityCachedVariantKeys;
- (bool)_accessibilityHasVariantKeys;
- (bool)_accessibilityIsTouchContainer;
- (bool)_accessibilityKeyboardKeyHasSignificantAlternateActions;
- (void)_accessibilitySetCachedVariantKeys:(id)arg1;
- (id)_accessibilityVariantKeys;
- (id)_axEmoji;
- (void)accessibilityElementDidBecomeFocused;
- (id)accessibilityHeaderElements;
- (id)accessibilityLabel;
- (struct _NSRange { unsigned long long x1; unsigned long long x2; })accessibilityRowRange;
- (unsigned long long)accessibilityTraits;
- (bool)isAccessibilityElement;
- (void)prepareForReuse;
- (void)setEmoji:(id)arg1;

@end
