/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIPrintPanelWindow : UIWindow

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (bool)_canAffectStatusBarAppearance;

// Image: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit

+ (Class)safeCategoryBaseClass;

- (bool)accessibilityViewIsModal;

@end
