/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarBluetoothItemView : UIStatusBarItemView {
    bool  _connected;
    bool  _shouldAnimateConnection;
}

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (void)_blinkAnimationDidStop:(id)arg1 finished:(id)arg2 context:(id)arg3;
- (double)alphaForConnected:(bool)arg1;
- (id)contentsImage;
- (void)performPendedActions;
- (void)setVisible:(bool)arg1;
- (bool)updateForNewData:(id)arg1 actions:(int)arg2;

// Image: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (bool)isAccessibilityElement;

@end
