/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarBatteryPercentItemView : UIStatusBarItemView {
    NSString * _percentString;
}

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (void).cxx_destruct;
- (bool)animatesDataChange;
- (id)contentsImage;
- (double)extraRightPadding;
- (long long)textAlignment;
- (long long)textStyle;
- (bool)updateForNewData:(id)arg1 actions:(int)arg2;

// Image: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit

+ (Class)safeCategoryBaseClass;

- (id)_accessibilityIsBatteryItemVisible;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (bool)isAccessibilityElement;

@end
