/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarDataNetworkItemView : UIStatusBarItemView {
    int  _dataNetworkType;
    bool  _enableRSSI;
    bool  _showRSSI;
    bool  _wifiLinkWarning;
    int  _wifiStrengthBars;
    int  _wifiStrengthRaw;
}

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (id)_dataNetworkImage;
- (id)_stringForRSSI;
- (id)contentsImage;
- (double)extraLeftPadding;
- (double)extraRightPadding;
- (double)maximumOverlap;
- (bool)updateForNewData:(id)arg1 actions:(int)arg2;

// Image: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityValue;
- (bool)isAccessibilityElement;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;

@end
