/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarSignalStrengthItemView : UIStatusBarItemView {
    bool  _enableRSSI;
    bool  _showRSSI;
    int  _signalStrengthBars;
    int  _signalStrengthRaw;
}

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (id)_stringForRSSI;
- (id)contentsImage;
- (double)extraRightPadding;
- (bool)updateForNewData:(id)arg1 actions:(int)arg2;

// Image: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (bool)isAccessibilityElement;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;

@end
