/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarPersonNameItemView : UIStatusBarItemView {
    double  _letterSpacing;
    double  _maxWidth;
    NSString * _personNameString;
}

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (void).cxx_destruct;
- (bool)_updateWithPersonName:(id)arg1 maxWidth:(double)arg2;
- (double)addContentOverlap:(double)arg1;
- (id)contentsImage;
- (long long)legibilityStyle;
- (double)resetContentOverlap;
- (double)standardPadding;
- (bool)updateForNewData:(id)arg1 actions:(int)arg2;

// Image: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (bool)isAccessibilityElement;

@end
