/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarDoubleHeightItemView : UIStatusBarItemView {
    NSString * _contentsString;
    bool  _ellipsize;
    double  _letterSpacing;
}

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (void).cxx_destruct;
- (id)contentsImage;
- (double)extraRightPadding;
- (bool)updateForNewData:(id)arg1 actions:(int)arg2;

// Image: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (bool)isAccessibilityElement;

@end
