/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarActivityItemView : UIStatusBarItemView {
    UIActivityIndicatorView * _activityIndicator;
    bool  _slowActivity;
    bool  _syncActivity;
}

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

- (void).cxx_destruct;
- (long long)_activityIndicatorStyle;
- (void)_startAnimating;
- (void)_stopAnimating;
- (void)setVisible:(bool)arg1;
- (double)shadowPadding;
- (double)updateContentsAndWidth;
- (bool)updateForNewData:(id)arg1 actions:(int)arg2;

// Image: /System/Library/AccessibilityBundles/UIKit.axbundle/UIKit

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (bool)isAccessibilityElement;

@end
