/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WeatherFoundation.framework/WeatherFoundation
 */

@interface WFAttribution : NSObject

@property (readonly) NSString *localizedSourceAttribution;
@property (readonly) NSURL *sourceAttributionURL;
@property (readonly) NSString *sourceName;

// Image: /System/Library/PrivateFrameworks/WeatherFoundation.framework/WeatherFoundation

+ (id)platformSpecializedWeatherSourceAttributionURLForTrafficParameter:(id)arg1;
+ (id)sharedAttribution;
+ (id)weatherSourceAttributionURLForTrafficParameter:(id)arg1;

- (id)localizedSourceAttribution;
- (id)sourceAttributionURL;
- (id)sourceName;

// Image: /System/Library/AccessibilityBundles/WeatherFramework.axbundle/WeatherFramework

+ (Class)safeCategoryBaseClass;

- (id)sourceAttributionImageForStyle:(unsigned long long)arg1;

@end
