/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
 */

@interface CCUIControlCenterSectionView : UIView {
    long long  _layoutStyle;
}

@property (nonatomic) long long layoutStyle;

// Image: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI

- (bool)_shouldAnimatePropertyWithKey:(id)arg1;
- (long long)layoutStyle;
- (void)setLayoutStyle:(long long)arg1;

// Image: /System/Library/AccessibilityBundles/ControlCenterUI.axbundle/ControlCenterUI

+ (Class)safeCategoryBaseClass;

- (bool)shouldGroupAccessibilityChildren;

@end
