/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
 */

@interface CCUINightShiftContentView : CCUIControlCenterSectionView {
    CCUIControlCenterPushButton * _button;
}

@property (nonatomic, readonly) CCUIControlCenterPushButton *button;

// Image: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI

- (void).cxx_destruct;
- (id)_selectedStateColor;
- (id)button;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (struct CGSize { double x1; double x2; })intrinsicContentSize;

// Image: /System/Library/AccessibilityBundles/ControlCenterUI.axbundle/ControlCenterUI

+ (Class)safeCategoryBaseClass;

- (void)_accessibilityLoadAccessibilityInformation;

@end
