/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

@interface MFHeaderLabelView : UILabel

// Image: /System/Library/Frameworks/MessageUI.framework/MessageUI

+ (id)_defaultColor;

- (struct CGPoint { double x1; double x2; })baselinePoint;
- (id)effectiveTextColor;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;

// Image: /System/Library/AccessibilityBundles/MessageUIFramework.axbundle/MessageUIFramework

+ (Class)safeCategoryBaseClass;

- (bool)_accessibilityIsScannerElement;
- (id)accessibilityHint;
- (bool)isAccessibilityElement;

@end
