# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Message Analyzer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Message Analyzer

  pod 'ATHMultiSelectionSegmentedControl'
  pod 'CrossroadRegex', '~> 1.0-alpha.1'

  pod 'RxSwift', '~> 3.0'
  pod 'RxCocoa', '~> 3.0'
  pod 'RxDataSources', '~> 1.0'
#  pod 'RxGesture'
  pod 'NSObject+Rx'
  
  target 'Message AnalyzerTests' do
    inherit! :search_paths
    # Pods for testing
    
    pod 'RxBlocking', '~> 3.0'
    pod 'RxTest',     '~> 3.0'
  end

  target 'Message AnalyzerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
