/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Memories.framework/Memories
 */

@interface MiroMemoryTitleStyleCollectionViewCell : UICollectionViewCell {
    UILabel * _label;
    UIImageView * _posterImageView;
}

@property (nonatomic, retain) UILabel *label;
@property (nonatomic, retain) UIImageView *posterImageView;

// Image: /System/Library/PrivateFrameworks/Memories.framework/Memories

- (void).cxx_destruct;
- (void)applyLayoutAttributes:(id)arg1;
- (id)label;
- (id)posterImageView;
- (void)setLabel:(id)arg1;
- (void)setLabelText:(id)arg1;
- (void)setPosterImageView:(id)arg1;
- (void)setSelected:(bool)arg1;

// Image: /System/Library/AccessibilityBundles/Memories.axbundle/Memories

+ (Class)safeCategoryBaseClass;

- (id)_axMoodName;
- (void)_axSetTitleMoodName:(id)arg1;
- (void)_setAXMoodName:(id)arg1;
- (id)accessibilityLabel;
- (bool)isAccessibilityElement;

@end
