/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AddressBook.framework/AddressBook
 */

@interface ABDynamicLoader : NSObject

// Image: /System/Library/Frameworks/AddressBook.framework/AddressBook

+ (bool)loadFrameworkAtPath:(id)arg1 andStoreHandle:(void**)arg2 bundle:(id*)arg3;

// Image: /System/Library/AccessibilityBundles/AddressBookUIFramework.axbundle/AddressBookUIFramework

+ (bool)loadFrameworkAtPath:(id)arg1 andStoreHandle:(void**)arg2 bundle:(id*)arg3 logging:(bool)arg4;
+ (Class)safeCategoryBaseClass;

@end
