/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIInlineCardSectionsTableViewCell : SearchUITableViewCell

// Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI

- (id)initWithResult:(id)arg1 style:(unsigned long long)arg2 feedbackDelegate:(id)arg3;
- (bool)supportsRecycling;

// Image: /System/Library/AccessibilityBundles/SearchUI.axbundle/SearchUI

+ (Class)safeCategoryBaseClass;

- (void)_accessibilityLoadAccessibilityInformation;
- (id)_axFirstRowWithID:(id)arg1 inRowSections:(id)arg2;
- (id)_axTableHeaderForColumn:(long long)arg1 withString:(id)arg2;
- (id)initWithResult:(id)arg1 style:(long long)arg2;
- (bool)isAccessibilityElement;

@end
