/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUITrailersCardSectionView : SearchUICardSectionView

// Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI

- (id)initWithCardSection:(id)arg1 controller:(id)arg2;

// Image: /System/Library/AccessibilityBundles/SearchUI.axbundle/SearchUI

+ (Class)safeCategoryBaseClass;

@end
