/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIIconView : UIView {
    NSLayoutConstraint * _bottomConstraint;
    SearchUITableViewCell * _cell;
    SearchUIForceTouchGestureRecognizer * _forceTouchRecognizer;
    SearchUIAppIconButton * _iconButton;
    UIView * _iconButtonContainer;
    UILabel * _label;
    SFSearchResult * _result;
}

@property (retain) NSLayoutConstraint *bottomConstraint;
@property (retain) SearchUITableViewCell *cell;
@property (retain) SearchUIForceTouchGestureRecognizer *forceTouchRecognizer;
@property (retain) SearchUIAppIconButton *iconButton;
@property (retain) UIView *iconButtonContainer;
@property (retain) UILabel *label;
@property (retain) SFSearchResult *result;

// Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI

+ (id)labelFont;

- (void).cxx_destruct;
- (id)bottomConstraint;
- (id)cell;
- (id)forceTouchRecognizer;
- (id)iconButton;
- (id)iconButtonContainer;
- (void)iconButtonPressed;
- (id)label;
- (id)result;
- (void)setBottomConstraint:(id)arg1;
- (void)setCell:(id)arg1;
- (void)setForceTouchRecognizer:(id)arg1;
- (void)setIconButton:(id)arg1;
- (void)setIconButtonContainer:(id)arg1;
- (void)setLabel:(id)arg1;
- (void)setResult:(id)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (void)updateWithResult:(id)arg1;
- (id)viewForFirstBaselineLayout;
- (id)viewForLastBaselineLayout;

// Image: /System/Library/AccessibilityBundles/SearchUI.axbundle/SearchUI

+ (Class)safeCategoryBaseClass;

- (bool)accessibilityElementsHidden;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (id)initWithStyle:(unsigned long long)arg1 cell:(id)arg2;
- (bool)isAccessibilityElement;

@end
