/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIScoreSummaryCardSectionView : SearchUICardSectionView

// Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI

- (id)initWithCardSection:(id)arg1 controller:(id)arg2;

// Image: /System/Library/AccessibilityBundles/SearchUI.axbundle/SearchUI

+ (Class)safeCategoryBaseClass;

- (id)_axSafariAccessibilityLabelForResult:(id)arg1;
- (id)_axScoreStringForType:(id)arg1 withLeftTeamName:(id)arg2 score:(id)arg3 rightTeamName:(id)arg4 score:(id)arg5;
- (id)accessibilityLabel;
- (bool)isAccessibilityElement;

@end
