/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXPeopleNamePickerTitleField : UITextField {
    double  _maxWidth;
}

@property (nonatomic) double maxWidth;

// Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore

- (struct CGSize { double x1; double x2; })intrinsicContentSize;
- (double)maxWidth;
- (void)setMaxWidth:(double)arg1;

// Image: /System/Library/AccessibilityBundles/PhotosUICore.axbundle/PhotosUICore

+ (Class)safeCategoryBaseClass;

- (id)accessibilityValue;

@end
