/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CameraKit.framework/CameraKit
 */

@interface DeferredFrameworkLoader : NSObject {
    void * _frameworkHandle;
    long long  _frameworkLoadedToken;
    NSString * _path;
}

@property (nonatomic) void*frameworkHandle;
@property (nonatomic) long long frameworkLoadedToken;
@property (nonatomic, retain) NSString *path;

// Image: /System/Library/PrivateFrameworks/CameraKit.framework/CameraKit

+ (id)PhotosUIFrameworkPath;

- (void).cxx_destruct;
- (void)dealloc;
- (void*)frameworkHandle;
- (long long)frameworkLoadedToken;
- (id)initWithPath:(id)arg1;
- (id)path;
- (void)setFrameworkHandle:(void*)arg1;
- (void)setFrameworkLoadedToken:(long long)arg1;
- (void)setPath:(id)arg1;

// Image: /System/Library/AccessibilityBundles/CameraKit.axbundle/CameraKit

+ (Class)safeCategoryBaseClass;

- (Class)classFromString:(id)arg1;

@end
