/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUQuickControlSwitchView : UIView <HUQuickControlControllableView> {
    UIView * _knobView;
    HUQuickControlSwitchViewProfile * _profile;
    double  _switchValue;
    UIView * _wellView;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) UIView *knobView;
@property (nonatomic, copy) HUQuickControlSwitchViewProfile *profile;
@property (nonatomic, retain) id secondaryValue;
@property (nonatomic) long long sizeSubclass;
@property (readonly) Class superclass;
@property (nonatomic) double switchValue;
@property (nonatomic, retain) id value;
@property (nonatomic, retain) UIView *wellView;

// Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI

- (void).cxx_destruct;
- (id)initWithProfile:(id)arg1;
- (id)knobView;
- (void)layoutSubviews;
- (id)profile;
- (void)setKnobView:(id)arg1;
- (void)setProfile:(id)arg1;
- (void)setSwitchValue:(double)arg1;
- (void)setValue:(id)arg1;
- (void)setWellView:(id)arg1;
- (double)switchValue;
- (id)value;
- (id)wellView;

// Image: /System/Library/AccessibilityBundles/HomeUI.axbundle/HomeUI

+ (Class)safeCategoryBaseClass;

- (id)_accessibilityContainerView;
- (void)_accessibilitySetSwitchValue:(double)arg1;
- (id)_accessibilitySummaryView;
- (bool)_accessibilitySupportsActivateAction;
- (bool)accessibilityActivate;
- (void)accessibilityDecrement;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })accessibilityFrame;
- (id)accessibilityIdentifier;
- (void)accessibilityIncrement;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityValue;
- (bool)isAccessibilityElement;

@end
