/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUTitleControlCell : HUControlPanelCell {
    UIView<HUControlView> * _controlView;
    NSArray * _controlViewConstraints;
    UILabel * _titleLabel;
    NSArray * _titleLabelConstraints;
}

@property (nonatomic, copy) NSString *controlTitle;
@property (nonatomic, retain) UIView<HUControlView> *controlView;
@property (nonatomic, copy) NSArray *controlViewConstraints;
@property (nonatomic, retain) UILabel *titleLabel;
@property (nonatomic, copy) NSArray *titleLabelConstraints;

// Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI

+ (bool)requiresConstraintBasedLayout;

- (void).cxx_destruct;
- (id)allControlViews;
- (id)controlTitle;
- (id)controlView;
- (id)controlViewConstraints;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)prepareForReuse;
- (void)setControlTitle:(id)arg1;
- (void)setControlView:(id)arg1;
- (void)setControlViewConstraints:(id)arg1;
- (void)setTitleLabel:(id)arg1;
- (void)setTitleLabelConstraints:(id)arg1;
- (id)titleLabel;
- (id)titleLabelConstraints;
- (void)updateConstraints;

// Image: /System/Library/AccessibilityBundles/HomeUI.axbundle/HomeUI

+ (Class)safeCategoryBaseClass;

- (id)_axControlElement;
- (struct CGPoint { double x1; double x2; })accessibilityActivationPoint;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityValue;
- (bool)isAccessibilityElement;

@end
