/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

@interface EKCalendarColorEditItem : EKCalendarEditItem {
    NSMutableArray * _cells;
    unsigned long long  _checkedRow;
}

@property (nonatomic, readonly) NSMutableArray *cells;

// Image: /System/Library/Frameworks/EventKitUI.framework/EventKitUI

- (void).cxx_destruct;
- (void)calendarEditor:(id)arg1 didSelectSubitem:(unsigned long long)arg2;
- (id)cellForSubitemAtIndex:(unsigned long long)arg1;
- (id)cells;
- (bool)configureWithCalendar:(id)arg1;
- (id)headerTitle;
- (unsigned long long)numberOfSubitems;
- (void)reset;
- (bool)saveStateToCalendar:(id)arg1;
- (void)setCalendar:(id)arg1 store:(id)arg2;

// Image: /System/Library/AccessibilityBundles/EventKitUIFramework.axbundle/EventKitUIFramework

+ (Class)safeCategoryBaseClass;

- (id)_cellForColor:(id)arg1;

@end
