/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

@interface EKEventDetailAttendeesCell : EKEventDetailCell {
    UIView<EKEventDetailAttendeesList> * _attendeesListView;
    bool  _useFaces;
    UIViewController * _viewController;
}

@property bool useFaces;
@property UIViewController *viewController;

// Image: /System/Library/Frameworks/EventKitUI.framework/EventKitUI

- (void).cxx_destruct;
- (id)_attendeesListView;
- (id)initWithEvent:(id)arg1 editable:(bool)arg2;
- (void)layoutForWidth:(double)arg1 position:(int)arg2;
- (void)setAttendees:(id)arg1;
- (void)setUseFaces:(bool)arg1;
- (void)setViewController:(id)arg1;
- (bool)update;
- (bool)useFaces;
- (id)viewController;

// Image: /System/Library/AccessibilityBundles/EventKitUIFramework.axbundle/EventKitUIFramework

+ (Class)safeCategoryBaseClass;

- (id)_axStringForParticipants:(id)arg1;
- (id)accessibilityLabel;

@end
