/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
 */

@interface EKRecurrenceTypeTableViewCell : EKUIConstrainedFontsTableViewCell {
    bool  _checked;
    UIView * _checkmarkView;
}

@property (getter=isChecked, nonatomic) bool checked;

// Image: /System/Library/Frameworks/EventKitUI.framework/EventKitUI

- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (bool)isChecked;
- (void)setChecked:(bool)arg1;

// Image: /System/Library/AccessibilityBundles/EventKitUIFramework.axbundle/EventKitUIFramework

+ (Class)safeCategoryBaseClass;

- (unsigned long long)accessibilityTraits;

@end
