/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVKit.framework/AVKit
 */

@interface AVTouchIgnoringView : UIView

// Image: /System/Library/Frameworks/AVKit.framework/AVKit

- (id)hitTest:(struct CGPoint { double x1; double x2; })arg1 withEvent:(id)arg2;

// Image: /System/Library/AccessibilityBundles/AVKit.axbundle/AVKit

+ (Class)safeCategoryBaseClass;

- (bool)_accessibilityObscuresScreen;
- (bool)accessibilityElementsHidden;

@end
