/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@interface MKNewAnnotationContainerView : MKAnnotationContainerView {
    bool  _suppress;
}

// Image: /System/Library/Frameworks/MapKit.framework/MapKit

- (void)_updateAddedAnnotationRotation:(id)arg1;
- (void)_updateAnnotationView:(id)arg1;
- (void)_updateAnnotationViewPerspective;
- (void)_updateAnnotationViewPositions;
- (void)setAnnotationViewsRotationRadians:(double)arg1 animation:(id)arg2;
- (void)stopSuppressingUpdates;
- (void)suppressUpdates;

// Image: /System/Library/AccessibilityBundles/MapKitFramework.axbundle/MapKitFramework

+ (Class)safeCategoryBaseClass;

- (bool)accessibilityElementsHidden;

@end
