/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@interface MKPlaceInfoPhoneNumberView : MKPlaceInfoContactRowView {
    bool  _optsOutOfAds;
    _MKUILabel * _optsOutOfAdsView;
}

@property (nonatomic) bool optsOutOfAds;

// Image: /System/Library/Frameworks/MapKit.framework/MapKit

- (void).cxx_destruct;
- (id)_iconAccessibilityLabel;
- (Class)_labeledValueExpectedValueType;
- (id)_valueString;
- (bool)optsOutOfAds;
- (void)setOptsOutOfAds:(bool)arg1;

// Image: /System/Library/AccessibilityBundles/MapKitFramework.axbundle/MapKitFramework

+ (Class)safeCategoryBaseClass;

- (id)_icon;

@end
