/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@interface MKPlaceInfoURLRowView : MKPlaceInfoContactRowView

// Image: /System/Library/Frameworks/MapKit.framework/MapKit

- (id)_iconAccessibilityLabel;
- (Class)_labeledValueExpectedValueType;
- (id)_valueString;

// Image: /System/Library/AccessibilityBundles/MapKitFramework.axbundle/MapKitFramework

+ (Class)safeCategoryBaseClass;

- (id)_icon;

@end
