/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SafariServices.framework/SafariServices
 */

@interface _SFBrowserNavigationBar : _SFNavigationBar

@property (nonatomic, readonly) _SFBrowserToolbar *toolbar;

// Image: /System/Library/Frameworks/SafariServices.framework/SafariServices

- (double)URLFieldHorizontalMargin;
- (id)newTextField;
- (double)placeholderHorizontalInset;
- (void)tintColorDidChange;
- (id)toolbar;
- (id)toolbarPlacedOnTop;
- (void)updateToobarTintColor;

// Image: /System/Library/AccessibilityBundles/SafariServices.axbundle/SafariServices

+ (Class)safeCategoryBaseClass;

- (bool)_accessibilityHitTestShouldFallbackToNearestChild;
- (bool)_accessibilityOnlyComparesByXAxis;
- (id)accessibilityElements;

@end
