/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

@interface MPTransportButton : MPButton {
    MPAVController * player;
}

@property (nonatomic, retain) MPAVController *player;

// Image: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer

- (void).cxx_destruct;
- (id)_automationID;
- (id)player;
- (void)setPlayer:(id)arg1;

// Image: /System/Library/AccessibilityBundles/MediaPlayerFramework.axbundle/MediaPlayerFramework

+ (Class)safeCategoryBaseClass;

- (id)accessibilityHint;
- (id)accessibilityIdentifier;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;

@end
