/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUAlbumListTableViewCell : UITableViewCell {
    <PUAlbumListTableViewCellDelegate> * _stateChangeDelegate;
}

@property (nonatomic) <PUAlbumListTableViewCellDelegate> *stateChangeDelegate;

// Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI

- (void).cxx_destruct;
- (void)setStateChangeDelegate:(id)arg1;
- (id)stateChangeDelegate;
- (void)willTransitionToState:(unsigned long long)arg1;

// Image: /System/Library/AccessibilityBundles/PhotosUIFramework.axbundle/PhotosUIFramework

+ (Class)safeCategoryBaseClass;

- (id)accessibilityLabel;
- (id)accessibilityValue;

@end
