/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKAvatarCollectionViewCell : UICollectionViewCell {
    CKAvatarView * _avatarView;
}

@property (nonatomic, retain) CKAvatarView *avatarView;

// Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit

+ (id)reuseIdentifier;

- (void).cxx_destruct;
- (id)avatarView;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)layoutSubviews;
- (void)setAvatarView:(id)arg1;

// Image: /System/Library/AccessibilityBundles/ChatKitFramework.axbundle/ChatKitFramework

+ (Class)safeCategoryBaseClass;

- (id)_axCKEntity;
- (void)_axSetCKEntity:(id)arg1;
- (void)_setAXCKEntity:(id)arg1;
- (id)accessibilityLabel;
- (void)configureWithEntity:(id)arg1;
- (bool)isAccessibilityElement;

@end
